version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directories:
      - "/safir"
      - "/safir-arq"
      - "/safir-logging"
    schedule:
      interval: "weekly"
