name: Python CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - 3.7
          - 3.8

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install tox
        run: pip install tox

      - name: Cache tox environments
        id: cache-tox
        uses: actions/cache@v1
        with:
          path: .tox
          # setup.cfg, pyproject.toml, and .pre-commit-config.yaml have
          # versioning info that would impact the tox environment. hashFiles
          # only takes a single file path or pattern at the moment.
          key: ${{ runner.os }}-${{ matrix.python }}-tox-${{ hashFiles('setup.cfg') }}-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run tox
        run: tox -e py,lint,typing  # run tox using Python in path
